CREATE DATABASE FlixNet
GO
USE FlixNet
GO

CREATE TABLE Producator(
Pid INT PRIMARY KEY IDENTITY,
Nume VARCHAR(60))

CREATE TABLE Filme(
Fid INT PRIMARY KEY IDENTITY,
Titlu VARCHAR(50),
Gen VARCHAR(30))

CREATE TABLE Seriale(
Sid INT PRIMARY KEY IDENTITY,
Titlu VARCHAR(50),
Gen VARCHAR(30),
NrEp INT NOT NULL,
Pid INT FOREIGN KEY REFERENCES Producator(Pid))

CREATE TABLE Actori(
Aid INT PRIMARY KEY IDENTITY,
Nume VARCHAR(30),
Prenume VARCHAR(30),
DataN DATE)

CREATE TABLE EnrolledF(
Fid INT FOREIGN KEY REFERENCES Filme(Fid),
Aid INT FOREIGN KEY REFERENCES Actori(Aid),
DataInceput DATE,
Salariu INT,
CONSTRAINT pk_EnrolledF PRIMARY KEY (Fid, Aid))

CREATE TABLE EnrolledS(
Sid INT FOREIGN KEY REFERENCES Seriale(Sid),
Aid INT FOREIGN KEY REFERENCES Actori(Aid),
DataInceput DATE,
Salariu INT,
CONSTRAINT pk_EnrolledS PRIMARY KEY (Sid, Aid))

CREATE TABLE Abonamente(
Abid INT PRIMARY KEY IDENTITY,
NrUtilizatori INT NOT NULL,
Mail VARCHAR(100))

CREATE TABLE Utilizatori(
Uid INT PRIMARY KEY IDENTITY,
Nickname VARCHAR(30) DEFAULT 'USER#',
DataN DATE,
Aid INT FOREIGN KEY REFERENCES Abonamente(Abid))

CREATE TABLE WatchlistF(
Fid INT FOREIGN KEY REFERENCES Filme(Fid),
Uid INT FOREIGN KEY REFERENCES Utilizatori(Uid),
DeVazut INT,
CONSTRAINT pk_WatchlistF PRIMARY KEY (Fid,Uid))

CREATE TABLE WatchlistS(
Sid INT FOREIGN KEY REFERENCES Seriale(Sid),
Uid INT FOREIGN KEY REFERENCES Utilizatori(Uid),
DeVazut INT,
CONSTRAINT pk_WatchlistS PRIMARY KEY (Sid,Uid))