CREATE DATABASE Facultate1
GO
USE Facultate1
GO
CREATE TABLE Grupe(
Gid INT PRIMARY KEY,
NrS INT NOT NULL)
CREATE TABLE Studenti(
Sid INT PRIMARY KEY IDENTITY,
Nume VARCHAR(50) DEFAULT 'Ionescu',
Prenume VARCHAR(50),
DataN DATE,
Gid INT FOREIGN KEY REFERENCES Grupe(Gid))
CREATE TABLE Sali(
Said INT PRIMARY KEY,
NrLocuri INT CHECK(NrLocuri>=20 AND NrLocuri<=30),
NrTable INT DEFAULT 1)
CREATE TABLE Orare(
Sid INT FOREIGN KEY REFERENCES Studenti(Sid),
Said INT FOREIGN KEY REFERENCES Sali(Said),
OraIn DATETIME,
OraSf DATETIME,
CONSTRAINT pk_Orare PRIMARY KEY (Sid, Said))
CREATE TABLE Mentori(
Mid INT FOREIGN KEY REFERENCES Grupe(Gid),
Nume VARCHAR(50) NOT NULL,
Varsta INT,
CONSTRAINT pk_Mentori PRIMARY KEY (Mid))
