CREATE DATABASE Netflix
GO
USE Netflix
GO

CREATE TABLE Producator(
Pid INT PRIMARY KEY,
Nume VARCHAR(60))

CREATE TABLE Filme(
Fid INT PRIMARY KEY,
Titlu VARCHAR(50),
Gen VARCHAR(30))

CREATE TABLE Seriale(
Sid INT PRIMARY KEY,
Titlu VARCHAR(50),
Gen VARCHAR(30),
NrEp INT NOT NULL,
Pid INT FOREIGN KEY REFERENCES Producator(Pid))

CREATE TABLE Actori(
Aid INT PRIMARY KEY IDENTITY,
Nume VARCHAR(30),
Prenume VARCHAR(30),
DataN DATE)

CREATE TABLE EnrolledF(
Fid INT FOREIGN KEY REFERENCES Filme(Fid),
Aid INT FOREIGN KEY REFERENCES Actori(Aid),
DataInceput DATE,
CONSTRAINT pk_EnrolledF PRIMARY KEY (Fid, Aid))

CREATE TABLE EnrolledS(
Sid INT FOREIGN KEY REFERENCES Seriale(Sid),
Aid INT FOREIGN KEY REFERENCES Actori(Aid),
DataInceput DATE,
CONSTRAINT pk_EnrolledS PRIMARY KEY (Sid, Aid))

CREATE TABLE Abonamente(
Abid INT PRIMARY KEY IDENTITY,
NrUtilizatori INT NOT NULL,
Mail VARCHAR(100))

CREATE TABLE Utilizatori(
Uid INT PRIMARY KEY IDENTITY,
Nickname VARCHAR(30) DEFAULT 'USER#',
DataN DATE,
Aid INT FOREIGN KEY REFERENCES Abonamente(Abid))

CREATE TABLE Watchlist(
Uid INT FOREIGN KEY REFERENCES Utilizatori(Uid),
NrFilme INT,
NrSeriale INT,
CONSTRAINT pk_Watchlist PRIMARY KEY (Uid))

CREATE TABLE WA(
Uid INT FOREIGN KEY REFERENCES Watchlist(Uid),
Aid INT FOREIGN KEY REFERENCES Actori(Aid),
CONSTRAINT pk_WA PRIMARY KEY(Uid,Aid))